const popularCoursesArray = [
  {
    id: 1, 
    image:
      'https://eduma.thimpress.com/wp-content/uploads/2022/06/course-14-400x300.jpg',
    title: 'Eduma Course Creation for Passive Income',
    count: [6, 123],
    price: '$223',
    features: {
      lectures: 7,
      quizzes: 0,
      duration: '1 hour',
      skillLevel: 'all Levels',
      lang: 'English',
      students: 2,
      assessments: 'Yes',
    },
    desc: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    certification:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    outcomed: [
      'Over 37 lectures and 55.5 hours of content!',
      'LIVE PROJECT End to End Software Testing Training Included.',
      'Learn Software Testing and Automation basics from a professional trainer from your own desk.',
      'Information packed practical training starting from basics to advanced testing techniques.',
      'Best suitable for beginners to advanced level users and who learn faster when demonstrated.',
      'Course content designed by considering current software testing technology and the job market.',
      'Practical assignments at the end of every session.',
      'Practical learning experience with live project work and examples.',
    ],
  },
  {
    id: 2,
    image:
      'https://eduma.thimpress.com/wp-content/uploads/2022/06/course-18-400x300.jpg',
    title: 'How to Teach English Online and Get Paid',
    count: [7, 9],
    price: '$39.00',
    features: {
      lectures: 7,
      quizzes: 0,
      duration: '9 hour',
      skillLevel: 'all Levels',
      lang: 'English',
      students: 8,
      assessments: 'Yes',
    },
    desc: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    certification:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    outcomed: [
      'Over 37 lectures and 55.5 hours of content!',
      'LIVE PROJECT End to End Software Testing Training Included.',
      'Learn Software Testing and Automation basics from a professional trainer from your own desk.',
      'Information packed practical training starting from basics to advanced testing techniques.',
      'Best suitable for beginners to advanced level users and who learn faster when demonstrated.',
      'Course content designed by considering current software testing technology and the job market.',
      'Practical assignments at the end of every session.',
      'Practical learning experience with live project work and examples.',
    ],
  },
  {
    id: 3,
    image:
      'https://eduma.thimpress.com/wp-content/uploads/2022/06/course-17-400x300.jpg',
    title: 'How To Create In-Demand Online Courses',
    count: [7, 2],
    price: '$223',
    features: {
      lectures: 5,
      quizzes: 2,
      duration: '9 hour',
      skillLevel: 'B1 Levels',
      lang: 'English',
      students: 13,
      assessments: 'No',
    },
    desc: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    certification:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    outcomed: [
      'Over 37 lectures and 55.5 hours of content!',
      'LIVE PROJECT End to End Software Testing Training Included.',
      'Learn Software Testing and Automation basics from a professional trainer from your own desk.',
      'Information packed practical training starting from basics to advanced testing techniques.',
      'Best suitable for beginners to advanced level users and who learn faster when demonstrated.',
      'Course content designed by considering current software testing technology and the job market.',
      'Practical assignments at the end of every session.',
      'Practical learning experience with live project work and examples.',
    ],
  },
  {
    id: 4,
    image:
      'https://eduma.thimpress.com/wp-content/uploads/2022/06/course-16-400x300.jpg',
    title: 'Instructional Design for Learning and Development',
    count: [6, 88],
    price: '$50.00',
    features: {
      lectures: 7,
      quizzes: 0,
      duration: '9 hour',
      skillLevel: 'all Levels',
      lang: 'English',
      students: 8,
      assessments: 'Yes',
    },
    desc: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    certification:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    outcomed: [
      'Over 37 lectures and 55.5 hours of content!',
      'LIVE PROJECT End to End Software Testing Training Included.',
      'Learn Software Testing and Automation basics from a professional trainer from your own desk.',
      'Information packed practical training starting from basics to advanced testing techniques.',
      'Best suitable for beginners to advanced level users and who learn faster when demonstrated.',
      'Course content designed by considering current software testing technology and the job market.',
      'Practical assignments at the end of every session.',
      'Practical learning experience with live project work and examples.',
    ],
  },
  {
    id: 5,
    image:
      'https://eduma.thimpress.com/wp-content/uploads/2022/06/course-14-400x300.jpg',
    title: 'Eduma Course Creation for Passive Income',
    count: [6, 123],
    price: '$223',
    features: {
      lectures: 7,
      quizzes: 0,
      duration: '9 hour',
      skillLevel: 'all Levels',
      lang: 'English',
      students: 8,
      assessments: 'Yes',
    },
    desc: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    certification:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    outcomed: [
      'Over 37 lectures and 55.5 hours of content!',
      'LIVE PROJECT End to End Software Testing Training Included.',
      'Learn Software Testing and Automation basics from a professional trainer from your own desk.',
      'Information packed practical training starting from basics to advanced testing techniques.',
      'Best suitable for beginners to advanced level users and who learn faster when demonstrated.',
      'Course content designed by considering current software testing technology and the job market.',
      'Practical assignments at the end of every session.',
      'Practical learning experience with live project work and examples.',
    ],
  },
  {
    id: 6,
    image:
      'https://eduma.thimpress.com/wp-content/uploads/2022/06/course-18-400x300.jpg',
    title: 'How to Teach English Online and Get Paid',
    count: [7, 9],
    price: '$39.00',
    features: {
      lectures: 7,
      quizzes: 0,
      duration: '9 hour',
      skillLevel: 'all Levels',
      lang: 'English',
      students: 8,
      assessments: 'Yes',
    },
    desc: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    certification:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    outcomed: [
      'Over 37 lectures and 55.5 hours of content!',
      'LIVE PROJECT End to End Software Testing Training Included.',
      'Learn Software Testing and Automation basics from a professional trainer from your own desk.',
      'Information packed practical training starting from basics to advanced testing techniques.',
      'Best suitable for beginners to advanced level users and who learn faster when demonstrated.',
      'Course content designed by considering current software testing technology and the job market.',
      'Practical assignments at the end of every session.',
      'Practical learning experience with live project work and examples.',
    ],
  },
  {
    id: 7,
    image:
      'https://eduma.thimpress.com/wp-content/uploads/2022/06/course-17-400x300.jpg',
    title: 'How To Create In-Demand Online Courses',
    count: [7, 2],
    price: '$223',
    features: {
      lectures: 7,
      quizzes: 0,
      duration: '9 hour',
      skillLevel: 'all Levels',
      lang: 'English',
      students: 8,
      assessments: 'Yes',
    },
    desc: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    certification:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    outcomed: [
      'Over 37 lectures and 55.5 hours of content!',
      'LIVE PROJECT End to End Software Testing Training Included.',
      'Learn Software Testing and Automation basics from a professional trainer from your own desk.',
      'Information packed practical training starting from basics to advanced testing techniques.',
      'Best suitable for beginners to advanced level users and who learn faster when demonstrated.',
      'Course content designed by considering current software testing technology and the job market.',
      'Practical assignments at the end of every session.',
      'Practical learning experience with live project work and examples.',
    ],
  },
  {
    id: 8,
    image:
      'https://eduma.thimpress.com/wp-content/uploads/2022/06/course-16-400x300.jpg',
    title: 'Instructional Design for Learning and Development',
    count: [6, 88],
    price: '$50.00',
    features: {
      lectures: 7,
      quizzes: 0,
      duration: '9 hour',
      skillLevel: 'all Levels',
      lang: 'English',
      students: 8,
      assessments: 'Yes',
    },
    desc: 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    certification:
      'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry’s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged.',
    outcomed: [
      'Over 37 lectures and 55.5 hours of content!',
      'LIVE PROJECT End to End Software Testing Training Included.',
      'Learn Software Testing and Automation basics from a professional trainer from your own desk.',
      'Information packed practical training starting from basics to advanced testing techniques.',
      'Best suitable for beginners to advanced level users and who learn faster when demonstrated.',
      'Course content designed by considering current software testing technology and the job market.',
      'Practical assignments at the end of every session.',
      'Practical learning experience with live project work and examples.',
    ],
  },
]
export default popularCoursesArray
